apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-mysql-pv
  namespace: ghost
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /appdata/ghost/mysql
    type: DirectoryOrCreate
