apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mysql-pvc
  namespace: ghost
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: ghost-mysql-pv
