apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: ghost
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef: # ← locks to your PVC, ArgoCD won't fight it
    namespace: ghost
    name: my-ghost-ghost-on-kubernetes-content
  hostPath:
    path: /appdata/ghost
    type: DirectoryOrCreate
