apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airtrail-db-pvc
  namespace: utilities
  labels:
    app: airtrail-db
    tier: storage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: airtrail-db-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airtrail-uploads-pvc
  namespace: utilities
  labels:
    app: airtrail
    tier: storage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: airtrail-uploads-pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
