apiVersion: v1
kind: PersistentVolume
metadata:
  name: subsyncarr-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /appdata/subsyncarr
    type: Directory # Directory or DirectoryOrCreate
