apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: utilities
  labels:
    app: glance
    tier: utilities
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: glance
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glance
        tier: utilities
    spec:
      volumes:
        - name: config
          configMap:
            name: glance-config
      containers:
        - name: glance
          image: glanceapp/glance
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
