apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-db-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Retain, Delete (automatic delete)
  hostPath:
    path: /appdata/speedtest-db
    type: DirectoryOrCreate # ← creates folder if doesn't exist
