apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-data
  namespace: monitoring
spec:
  storageClassName: ""
  volumeName: speedtest-tracker-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
