apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-tracker-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /appdata/speedtest_tracker/data
    type: Directory
