apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: utilities
  labels:
    app: open-webui
    tier: utilities
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
