# argocd/apps/ghost.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kevin000001505/Homelab.git
    targetRevision: HEAD
    path: apps/utilities/ghost
  destination:
    server: https://192.168.1.15:6443
    namespace: ghost
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
