# argocd/apps/loki.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "7.0.0"
      helm:
        valueFiles:
          - $values/apps/monitoring/loki/values.yaml
    - repoURL: https://github.com/kevin000001505/Homelab.git
      targetRevision: HEAD
      ref: values # this becomes the $values alias
  destination:
    server: https://192.168.1.15:6443
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
