# argocd/apps/prometheus.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "86.3.2"
      helm:
        valueFiles:
          - $values/core/prometheus/values.yaml
    - repoURL: https://github.com/kevin000001505/Homelab.git
      targetRevision: HEAD
      ref: values # this becomes the $values alias
  destination:
    server: https://192.168.1.15:6443
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
