# argocd/apps/promtail.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: "6.17.1"
      helm:
        valueFiles:
          - $values/apps/monitoring/promtail/values.yaml
    - repoURL: https://github.com/kevin000001505/Homelab.git
      targetRevision: HEAD
      ref: values # this becomes the $values alias
  destination:
    server: https://192.168.1.15:6443
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
