apiVersion: v1
kind: PersistentVolume
metadata:
  name: dawarich-public-pv
spec:
  volumeMode: Filesystem
  hostPath:
    path: /appdata/dawarich/public
    type: DirectoryOrCreate
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
